language: node_js
node_js:
  - node

before_deploy:
  - npm run build:prod
deploy:
  skip_cleanup: true
  provider: firebase
  on:
    branch: master
  token: $FIREBASE_TOKEN
  project: gdg-torino-website

branches:
  only:
    - master

